database:
  # PostgreSQL database connection settings.
  host: "localhost:5432"
  host_env: "EELBOT_DB_HOST" # The environment variable value to use (used only if "host" is not set).
  database: "eelbot"
  database_env: "EELBOT_DB_NAME" # The environment variable value to use (used only if "database" is not set).
  database_file: "/run/secrets/pgdb" # The file name to load the value from (used only if "database" is not set).
  username: "eelbot"
  username_env: "EELBOT_DB_USER" # The environment variable value to use (used only if "username" is not set).
  username_file: "/run/secrets/pguser" # The file name to load the value from (used only if "username" is not set).
  password: "mysecretpassword"
  password_env: "EELBOT_DB_PASSWORD" # The environment variable value to use (used only if "password" is not set).
  password_file: "/run/secrets/pgpass" # The file name to load the value from (used only if "password" is not set).
  timeout: 10 # Timeout (in seconds) for database transactions.

commands:
  # /badjoke command (requires a database).
  badjoke:
    enable: true
    delay: 3 # Time (in seconds) to wait before saying the punchline of a multiline joke.

  # /eel command (requires a database).
  eel:
    enable: true

  # /taunt command (requires a database).
  taunt:
    enable: true

  # /channel command.
  channel:
    enable: true

  # /flip command.
  flip:
    enable: true

  # /listen command.
  listen:
    enable: true

  # /play command.
  play:
    enable: true

  # /ping command.
  ping:
    enable: true

  # /roll command.
  roll:
    enable: true

  # /say command.
  say:
    enable: true

  # /saychan command.
  saychan:
    enable: true

replies:
  # Add custom replies by creating a table under the `reply` schema in the database first, then adding an entry here to
  # reference it. Check the README for more details.
  - table_name: "myreply"
    regexps:
    - "a{3,6}"
    percent: 33
    min_delay: 3
    max_delay: 6
    timeout: 600
