name: Go
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v1
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
      - name: Build
        run: |
          go build -o ./bin/ ./cmd/...
